[blizzard]

# Set Blizzard API region & locale
# More: https://community.developer.battle.net/documentation/guides/regionality-and-apis
api_region = "eu"
api_base_url = "https://eu.api.blizzard.com"
api_locale = "en_GB"

# ⚠️ Highly recommended to use environment variables instead of hardcoding those secret values !
#api_client_id = ""
#api_client_secret = ""

[storage]

# Either local or s3
type = "local"

compression = "snappy"

[storage.local]

# Local directory where data files will be stored if type is set to "local"
# Note: this directory must already exists and be writeable
root_directory = "/tmp/wow-analytics-ah"

[storage.s3]

# URL of the S3 compatible endpoint: AWS S3 API, Cloudflare R2, etc...
endpoint_url = "https://s3.us-east-1.amazonaws.com"

# S3 region
region = "us"

bucket = "wow-analytics-data"

# Prefix used as a root for all objects
prefix = ""

# ⚠️ Highly recommended to use environment variables instead of hardcoding those secret values !
# access_key_id = ""
# access_key_secret = ""
